### ISSUE TITLE
Can't build app

### ISSUE THREAD

**Issue by DeadNumbers** [hackjutsu/Lepton#293]
#### Environment info
* OS: Arch Linux
```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/Work/Git/lepton-snippet-manager-git/src/lepton-snippet-manager/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Linux 4.16.9-1-hardened
gyp ERR! command "/usr/bin/node" "/home/user/Work/Git/lepton-snippet-manager-git/src/lepton-snippet-manager/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/user/Work/Git/lepton-snippet-manager-git/src/lepton-snippet-manager/node_modules/node-sass
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-codemirror@1.0.0 requires a peer of react@>=15.5 <16 but none is installed. You must install peer dependencies yourself.
npm WARN react-codemirror@1.0.0 requires a peer of react-dom@>=15.5 <16 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-05-23T10_50_33_104Z-debug.log
==> ERROR: A failure occurred in build().
    Aborting...
```
Full debug log https://gist.github.com/052dc5771645c2cc38e7f7ba98ef2bb4

**Comment by hackjutsu** [comment]
Thanks for reporting!

Which version and distribution of Linux did you use? Could you shiw us the steps to reproduce the issue?

**Comment by DeadNumbers** [comment]
@hackjutsu i'm use Arch Linux https://archlinux.org this is rolling release distributive. Install Lepton from AUR https://aur.archlinux.org/packages/lepton-snippet-manager-git/

Command to build
```bash
build() {
    cd "$srcdir/$_pkgname"
    sed -i 's/^.*"electron".*$//;s/^.*"electron-builder".*$//' package.json
    npm i
    npm run build
}
```
Full PKGBUILD can see https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lepton-snippet-manager-git

If I understood correctly, this string `sed -i 's/^.*"electron".*$//;s/^.*"electron-builder".*$//' package.json` change to local installed electron for build app. Version of local electron is
```
$ electron -v
v1.8.4
```

**Comment by hackjutsu** [comment]
@DeadNumbers 

Sorry, I didn't publish Lepton to that website and no idea of what their instructions are about. Please follow the readme in GitHub and have a try :)
