### ISSUE TITLE
Sync failed: Please check your network connections

### ISSUE THREAD

**Issue by gullevek** [hackjutsu/Lepton#381]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: macOS Mojave 10.14.6
* App Version (`Command/Ctrl + ,`): 1.8.1

#### Description of the problem / feature request / question:

First time install, DMG image copy to Applications folder.
Login seems to work (I see the login page and then the 2nd auth page) but after that the error "Sync failed: Please check your network connections" appears.

I can access github, gists, etc pages from my system perfectly fine.

#### If possible, provide the log files
2019-10-08T05:53:31.618Z - info:

----- Lepton v1.8.1 darwin-----

2019-10-08T05:53:31.619Z - info: [conf] Looking for .leptonrc at /Users/<USERNAME>/.leptonrc
2019-10-08T05:53:31.619Z - info: [conf] The resolved configuration is ...
2019-10-08T05:53:31.619Z - info: "theme": "light"
2019-10-08T05:53:31.619Z - info: "userPanel": {"hideProfilePhoto":false}
2019-10-08T05:53:31.619Z - info: "logger": {"level":"debug"}
2019-10-08T05:53:31.619Z - info: "proxy": {"enable":false,"address":"socks://localhost:1080"}
2019-10-08T05:53:31.619Z - info: "snippet": {"sorting":"updated_at","sortingReverse":true,"expanded":true,"newSnippetPrivate":false}
2019-10-08T05:53:31.619Z - info: "editor": {"tabSize":4}
2019-10-08T05:53:31.619Z - info: "enterprise": {"enable":false,"host":"","token":"","avatarUrl":""}
2019-10-08T05:53:31.620Z - info: "type": "literal"
2019-10-08T05:53:31.807Z - info: Checking for update
2019-10-08T05:53:31.886Z - debug: -----> registering login-page-ready listener
2019-10-08T05:53:33.427Z - debug: -----> Inside getCachedUserInfo
2019-10-08T05:53:33.429Z - debug: -----> [false] cachedProfile is undefined
2019-10-08T05:53:33.432Z - debug: -----> [false] cachedToken is undefined
2019-10-08T05:53:33.440Z - debug: -----> Inside LoginPage componentWillMount with loggedInUserInfonull
2019-10-08T05:53:33.440Z - debug: -----> Registering listener for auto-login signal
2019-10-08T05:53:33.441Z - debug: -----> sending login-page-ready signal
2019-10-08T05:53:33.441Z - info: [signal] sending auto-login signal
2019-10-08T05:53:33.551Z - debug: -----> Received "auto-login" signal with loggedInUserInfo null
2019-10-08T05:53:34.039Z - info: Update for version 1.8.1 is not available (latest version: 1.8.1, downgrade is disallowed).
2019-10-08T05:53:34.040Z - debug: checkForUpdatesAndNotify called, downloadPromise is null
2019-10-08T05:53:36.361Z - debug: -----> Inside launchAuthWindow with token undefined
2019-10-08T05:53:36.371Z - debug: loading authUrl https://github.com/login/oauth/authorize?client_id=9e42611bb02db4547abf&scope=gist
2019-10-08T05:53:36.380Z - info: [Dispatch] updateAuthWindowStatus ON
2019-10-08T05:53:58.713Z - info: [Dispatch] updateAuthWindowStatus OFF
2019-10-08T05:53:58.715Z - info: [Dispatch] updateUserSession IN_PROGRESS
2019-10-08T05:53:58.719Z - debug: [REST] Exchanging authCode with access token
2019-10-08T05:53:58.756Z - error: Failed: {"code":"SELF_SIGNED_CERT_IN_CHAIN"}
2019-10-08T05:55:54.536Z - error:  message=Cannot read property 'removeListener' of undefined, stack=TypeError: Cannot read property 'removeListener' of undefined
    at Object.unregisterAll (/Applications/Lepton.app/Contents/Resources/app.asar/node_modules/electron-localshortcut/index.js:91:20)
    at App.app.on (/Applications/Lepton.app/Contents/Resources/app.asar/main.js:164:29)
    at App.emit (events.js:182:13)

**Comment by alexandreamadocastro** [comment]
I got this error when the `.leptonrc` file is not a valid `json`, give it a try.

**Comment by hackjutsu** [comment]
https://github.com/hackjutsu/Lepton/issues/250

**Comment by RickyLiu0w0** [comment]
I had the same warning when I first time used this app. However, it has worked successfully since I quit it and run it again.
