### ISSUE TITLE
Auto-update doesn't work without code-sign on macOS 

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#385]
Need to double check but it seems the autoupdate is not working.

**Comment by ArtemKolichenkov** [comment]
@hackjutsu quite a coincidence - I just now remembered that I had Lepton installed, haven't used it since forever. Launched it and went to github to check how the project is doing - there are new versions but mine stays at 1.7.0 Also there is no button to manually update/check for updates.

**Comment by hackjutsu** [comment]
@ArtemKolichenkov Thanks for checking back! Yes, the auto-update is not working after 1.7 and need to be fixed.

**Comment by hackjutsu** [comment]
It's caused by the missing of code-sign. Maybe I should simply comment out the auto update logic.
https://stackoverflow.com/q/42286648

```
2020-03-21T22:23:56.096Z - warn:  message=Could not get code signature for running application, stack=Error: Could not get code signature for running application
    at Server.server.listen (/Applications/Lepton.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:170:32)
    at Object.onceWrapper (events.js:273:13)
    at Server.emit (events.js:182:13)
    at emitListeningNT (net.js:1320:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2020-03-21T22:23:56.096Z - error: Error: Error: Could not get code signature for running application
    at Server.server.listen (/Applications/Lepton.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:170:32)
    at Object.onceWrapper (events.js:273:13)
    at Server.emit (events.js:182:13)
    at emitListeningNT (net.js:1320:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by hackjutsu** [comment]
https://github.com/hackjutsu/Lepton/commit/76316f137dec989fa6c19d4e54149cff862b94f3
