### ISSUE TITLE
`npm i ddd` report  contextify@0.1.15 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by hye** [hackjutsu/Lepton#62]
依赖装不上-。-

- Ubuntu `16.10` （Yakkety Yak）
   Linux HOSTNAME 4.8.0-22-generic #24-Ubuntu SMP Sat Oct 8 09:15:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- npm -v  `4.1.2`
- node -v `v7.5.0`
- node-gyp -v `v3.5.0`

http_proxy via aliyun HK SS
```
$ http_proxy=http://localhost:8123 npm i ddd

> contextify@0.1.15 install /home/hye/apps/Lepton/node_modules/contextify
> node-gyp rebuild

make: Entering directory '/home/hye/apps/Lepton/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc: In static member function ‘static v8::Local<v8::Context> ContextWrap::createV8Context(v8::Local<v8::Object>)’:
../src/contextify.cc:131:68: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                                    ^
In file included from /home/hye/.node-gyp/7.5.0/include/node/v8.h:26:0,
                 from /home/hye/.node-gyp/7.5.0/include/node/node.h:42,
                 from ../src/contextify.cc:1:
/home/hye/.node-gyp/7.5.0/include/node/v8.h:3292:52: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                    ^
/home/hye/.node-gyp/7.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/contextify.cc:150:16: error: ‘class v8::ObjectTemplate’ has no member named ‘SetAccessCheckCallbacks’; did you mean ‘SetAccessCheckCallback’?
         otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
                ^~~~~~~~~~~~~~~~~~~~~~~
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyGetter(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&)’:
../src/contextify.cc:182:80: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                                                                              ^
In file included from /home/hye/.node-gyp/7.5.0/include/node/v8.h:26:0,
                 from /home/hye/.node-gyp/7.5.0/include/node/node.h:42,
                 from ../src/contextify.cc:1:
/home/hye/.node-gyp/7.5.0/include/node/v8.h:2949:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/hye/.node-gyp/7.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyQuery(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Integer>&)’:
../src/contextify.cc:209:67: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
                                                                   ^
In file included from /home/hye/.node-gyp/7.5.0/include/node/v8.h:26:0,
                 from /home/hye/.node-gyp/7.5.0/include/node/node.h:42,
                 from ../src/contextify.cc:1:
/home/hye/.node-gyp/7.5.0/include/node/v8.h:2949:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/hye/.node-gyp/7.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/contextify.cc:210:71: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
           !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
                                                                     ^
In file included from /home/hye/.node-gyp/7.5.0/include/node/v8.h:26:0,
                 from /home/hye/.node-gyp/7.5.0/include/node/node.h:42,
                 from ../src/contextify.cc:1:
/home/hye/.node-gyp/7.5.0/include/node/v8.h:2949:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/hye/.node-gyp/7.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
contextify.target.mk:94: recipe for target 'Release/obj.target/contextify/src/contextify.o' failed
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
make: Leaving directory '/home/hye/apps/Lepton/node_modules/contextify/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.8.0-22-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/hye/apps/Lepton/node_modules/contextify
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 

```

**Comment by hackjutsu** [comment]
没在Linux上测试过，似乎是node-gyp模块问题。我是用macOS开发的>_<

这个issue个人无能为力（汗。。。）

**Comment by hye** [comment]
:crying_cat_face:  那算了，我先只在macOS上用好了
我换个nodejs lts版本 试试先

**Comment by hackjutsu** [comment]
所报错涉及v8的native module，也许是node在新版本里把v8的api做了修改。

抱歉，没有Linux machine，帮不上忙。

**Comment by hye** [comment]
@hackjutsu  我也是才在windows的设备上装不上，才安的Linux，Ubuntu  16.10 desktop，所以版本号都很新-。-

**Comment by hackjutsu** [comment]
@hye 如果你不需要打包发布，可以试着把`electron-builder`这个依赖去掉。由于这个依赖负责build各平台的执行文件，涉及一些native的部件，容易出错。

**Comment by hye** [comment]
node -v `v6.9.5`
npm -v `3.10.10`
:100: works!
文档里加个建议nodejs版本吧

还有 readme `npm run pack` 
 package.json scripts里并没有`pack`

**Comment by wujysh** [comment]
还有 readme npm run pack
    package.json scripts里并没有pack
@hye It's fixed in #61.

**Comment by hye** [comment]
@wujysh  :+1: 
 我之是用里面npm run watch代替了-。-

and 10086 X  :+1:  for @hackjutsu

**Comment by hackjutsu** [comment]
@wujysh 我是前两天忘记`pack`有什么用，一时手抖删除了，因为开发时候主要用`webpack --watch`
